import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-screen">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <div className="container">
          <Navbar />
          <main className="flex-1 py-6">
              {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
